FROM mcr.microsoft.com/windows/servercore:ltsc2022

LABEL org.opencontainers.image.title="Windows Server Core LTSC 2022 Golden Image" \
      org.opencontainers.image.description="Windows Server Core LTSC 2022 base" \
      org.opencontainers.image.version="ltsc2022" \
      org.opencontainers.image.vendor="Golden Images"

CMD ["powershell.exe"]
