FROM mcr.microsoft.com/windows/servercore:ltsc2025

LABEL org.opencontainers.image.title="Windows Server Core LTSC 2025 Golden Image" \
      org.opencontainers.image.description="Windows Server Core LTSC 2025 base" \
      org.opencontainers.image.version="ltsc2025" \
      org.opencontainers.image.vendor="Golden Images"

CMD ["powershell.exe"]
