# Hadolint config for golden Ubuntu base images
# https://github.com/hadolint/hadolint

# Use latest packages for security updates (reproducibility via rebuild)
ignored:
  - DL3008  # Pin versions in apt get install
  - DL3015  # Avoid additional packages in apt-get install (we need ca-certificates and curl)

# Require explicit pinning of base image (we use ubuntu:18.04 etc.)
trustedRegistries:
  - docker.io
  - gcr.io
  - ghcr.io
